(module
	(memory 1)
	(global $stacktop (mut i32) (i32.const 64000))
	(func $main (result i32)
		(get_global $stacktop)
		(i32.const 4)
		(i32.sub)
		(set_global $stacktop)
		(get_global $stacktop)
		(i32.const 0)
		(i32.store)
	)
	(export "main" (func $main))
)